import { describe, it, expect } from 'vitest';
import {
  TRIAGE_DISCLAIMER,
  withTriageDisclaimer,
  classifyCreateInput,
  CreateInputError,
} from './issue-store';
import type { CreateInput } from './issue-store';

describe('withTriageDisclaimer (ADR-0015)', () => {
  it('prepends the verbatim AI-provenance disclaimer, blank-line separated', () => {
    expect(TRIAGE_DISCLAIMER).toBe('> *This was generated by AI during triage.*');
    expect(withTriageDisclaimer('Agent Brief here')).toBe(
      '> *This was generated by AI during triage.*\n\nAgent Brief here',
    );
  });
});

// ── classifyCreateInput — the whole-input create contract (ADR-0027, #278/#309)
//
// These are the LAYER specs: the classifier is called directly, with no store
// and no CLI in the picture at all, because that is the claim under test — the
// create-shape invariants are properties of this function, so every caller
// (every adapter's `create()`, the issue-store CLI, any future driver) inherits
// them rather than re-deriving one of them at its own edge.
describe('classifyCreateInput (ADR-0027) — shape classification', () => {
  const BARE: CreateInput = {
    title: 'Gate 8 ships inert',
    filingHint: 'gate-8-ships-inert',
    bodySections: [
      { heading: 'Gap', markdown: 'the verify config is never threaded through.' },
      { heading: 'Provenance', markdown: 'wave hardening, row 3, iteration 1.' },
    ],
  };

  const DECORATED: CreateInput = {
    title: 'A real slice',
    filingHint: 'a-real-slice',
    risk: 'mechanical',
    worker: 'background',
    files: ['src/x.ts'],
    blockedBy: 'none',
    acceptanceCriteria: [{ text: 'does the thing', checked: false }],
  };

  it('classifies a bare input (title + filingHint + authored bodySections) as bare', () => {
    expect(classifyCreateInput(BARE)).toEqual({ kind: 'bare' });
  });

  it('classifies a full Header-Block as decorated and hands back the narrowed input', () => {
    const shape = classifyCreateInput(DECORATED);
    expect(shape.kind).toBe('decorated');
    if (shape.kind === 'decorated') expect(shape.input.risk).toBe('mechanical');
  });

  // The negative control for the bare-body rule below: `bodySections` is
  // optional for a DECORATED input and must STAY optional — a decorated issue
  // has a Header-Block, so it is never a 0-body-char filing. If the requirement
  // ever leaks out of the bare branch, this is the case that fails.
  it('a DECORATED input with NO bodySections is still classified, not rejected', () => {
    expect(DECORATED.bodySections).toBeUndefined();
    expect(classifyCreateInput(DECORATED).kind).toBe('decorated');
    expect(classifyCreateInput({ ...DECORATED, bodySections: [] }).kind).toBe('decorated');
    expect(
      classifyCreateInput({
        ...DECORATED,
        bodySections: [{ heading: 'What to build', markdown: '   ' }],
      }).kind,
    ).toBe('decorated');
  });
});

// The typed rejection below is PUBLIC API as of issue #325: `CreateInputError`
// and `CreateInputFailure` are re-exported from the package root. Its pairing —
// same class binding across the barrel, so a root consumer's `instanceof` matches
// what these adapters throw — is asserted in `index.spec.ts`, the file that owns
// pairings spanning more than one module. These stay the LAYER specs: what the
// classifier rejects and why, with no barrel in the picture.
describe('classifyCreateInput — typed rejections (#309: the classifier owns the invariant)', () => {
  /** Run the classifier and return the CreateInputError it threw. */
  function rejectionOf(input: CreateInput): CreateInputError {
    try {
      classifyCreateInput(input);
    } catch (err) {
      expect(err).toBeInstanceOf(CreateInputError);
      return err as CreateInputError;
    }
    throw new Error('expected classifyCreateInput to reject, but it returned');
  }

  const TITLE = { title: 'Gate 8 ships inert', filingHint: 'gate-8-ships-inert' };

  it('a BARE input with bodySections ABSENT is rejected as `bare-without-body`', () => {
    const err = rejectionOf({ ...TITLE });
    expect(err.failure).toBe('bare-without-body');
    expect(err.fields).toEqual(['bodySections']);
    expect(err.code).toBe('create-input-invalid');
    expect(err.name).toBe('CreateInputError');
  });

  it('a BARE input with bodySections `[]` is rejected the same way', () => {
    expect(rejectionOf({ ...TITLE, bodySections: [] }).failure).toBe('bare-without-body');
  });

  it('a BARE input whose bodySections markdown is ALL BLANK is rejected the same way', () => {
    const err = rejectionOf({
      ...TITLE,
      bodySections: [
        { heading: 'Gap', markdown: '   ' },
        { heading: 'Provenance', markdown: '' },
      ],
    });
    expect(err.failure).toBe('bare-without-body');
  });

  it('ONE non-blank section is enough — the rule asks for authored content, not for every section to carry it', () => {
    expect(
      classifyCreateInput({
        ...TITLE,
        bodySections: [
          { heading: 'Gap', markdown: '   ' },
          { heading: 'Provenance', markdown: 'wave hardening, row 3, iteration 1.' },
        ],
      }),
    ).toEqual({ kind: 'bare' });
  });

  // Message quality is what the CLI renders; the rejection is what it routes on.
  // Both are pinned here so the layer move cannot quietly degrade the operator-
  // facing text into a bare "invalid input".
  it('the bare-body message names the field to fix and what would otherwise be filed', () => {
    const message = rejectionOf({ ...TITLE }).message;
    expect(message).toContain('bodySections');
    expect(message).toContain('no body at all');
    expect(message).toContain('Header-Block');
  });

  it('a HALF-WRITTEN Header-Block is rejected as `header-block-half-written`, naming the missing fields', () => {
    const err = rejectionOf({ ...TITLE, risk: 'mechanical' });
    expect(err.failure).toBe('header-block-half-written');
    expect(err.fields).toEqual(['worker', 'files', 'blockedBy', 'acceptanceCriteria']);
    expect(err.message).toMatch(/half-written/i);
  });

  it('a decoration-only stowaway on a bare input is rejected as `bare-carries-decoration-only-fields`', () => {
    const err = rejectionOf({ ...TITLE, parent: 'some-prd-id' });
    expect(err.failure).toBe('bare-carries-decoration-only-fields');
    expect(err.fields).toEqual(['parent']);
  });

  // Precedence: the stowaway verdict is the more specific claim about a
  // bodyless bare input, so it must not be masked by the body rule.
  it('a bodyless bare input carrying a stowaway reports the stowaway, not the missing body', () => {
    expect(rejectionOf({ ...TITLE, unblocks: [{ issue: 7 }] }).failure).toBe(
      'bare-carries-decoration-only-fields',
    );
  });

  it('every rejection is a real Error subclass (catchable by generic handlers too)', () => {
    const err = rejectionOf({ ...TITLE });
    expect(err).toBeInstanceOf(Error);
    expect(err.stack).toBeTruthy();
  });
});

// #530: a bare bodySections entry that is present but MALFORMED — a missing
// heading, a missing markdown, a blank heading, or a non-string value — used
// to sail past classification (markdown present and non-blank is enough for
// `hasBareBodyContent` to call the input non-empty) and crash three frames
// later inside a tracker adapter's serializer with a raw, un-teaching
// `TypeError: Cannot read properties of undefined (reading 'trim')`. These
// specs pin the typed, teaching refusal in its place — the SAME
// `bare-without-body` discriminant an absent/empty/all-blank `bodySections`
// already throws (the fix direction's "same teaching shape the
// missing-bodySections error already has"), distinguished by `err.fields`
// (a dotted per-entry path here, plain `['bodySections']` there) rather than
// by a new public union member.
describe('classifyCreateInput — a malformed bodySections entry on a BARE input (#530)', () => {
  function rejectionOf(input: CreateInput): CreateInputError {
    try {
      classifyCreateInput(input);
    } catch (err) {
      expect(err).toBeInstanceOf(CreateInputError);
      return err as CreateInputError;
    }
    throw new Error('expected classifyCreateInput to reject, but it returned');
  }

  const TITLE = { title: 'Gate 8 ships inert', filingHint: 'gate-8-ships-inert' };

  it('an entry missing `heading` (markdown present) is refused — no TypeError, nothing filed', () => {
    const err = rejectionOf({
      ...TITLE,
      bodySections: [
        { markdown: 'the verify config is never threaded through.' } as unknown as {
          heading: string;
          markdown: string;
        },
      ],
    });
    expect(err.failure).toBe('bare-without-body');
    expect(err.fields).toEqual(['bodySections[0].heading']);
    expect(err.code).toBe('create-input-invalid');
  });

  it('an entry missing `markdown` (heading present) is refused the same way', () => {
    const err = rejectionOf({
      ...TITLE,
      bodySections: [
        { heading: 'Gap' } as unknown as { heading: string; markdown: string },
      ],
    });
    expect(err.failure).toBe('bare-without-body');
    expect(err.fields).toEqual(['bodySections[0].markdown']);
  });

  it('an entry with a BLANK (whitespace-only) heading is refused', () => {
    const err = rejectionOf({
      ...TITLE,
      bodySections: [{ heading: '   ', markdown: 'authored prose here.' }],
    });
    expect(err.failure).toBe('bare-without-body');
    expect(err.fields).toEqual(['bodySections[0].heading']);
  });

  it('a non-string heading value is refused (not just an absent one)', () => {
    const err = rejectionOf({
      ...TITLE,
      bodySections: [
        { heading: 42, markdown: 'authored prose here.' } as unknown as {
          heading: string;
          markdown: string;
        },
      ],
    });
    expect(err.failure).toBe('bare-without-body');
    expect(err.fields).toEqual(['bodySections[0].heading']);
  });

  it('a non-string markdown value is refused (not just an absent one)', () => {
    const err = rejectionOf({
      ...TITLE,
      bodySections: [
        { heading: 'Gap', markdown: null } as unknown as {
          heading: string;
          markdown: string;
        },
      ],
    });
    expect(err.failure).toBe('bare-without-body');
    expect(err.fields).toEqual(['bodySections[0].markdown']);
  });

  it('both fields malformed in the same entry are named together', () => {
    const err = rejectionOf({
      ...TITLE,
      bodySections: [{ heading: '', markdown: undefined } as unknown as {
        heading: string;
        markdown: string;
      }],
    });
    expect(err.fields).toEqual(['bodySections[0].heading', 'bodySections[0].markdown']);
  });

  it('names the offending entry INDEX when the malformed entry is not the first', () => {
    const err = rejectionOf({
      ...TITLE,
      bodySections: [
        { heading: 'Gap', markdown: 'fine.' },
        { markdown: 'this one is missing its heading.' } as unknown as {
          heading: string;
          markdown: string;
        },
      ],
    });
    expect(err.fields).toEqual(['bodySections[1].heading']);
  });

  it('the message names the entry, the offending field, and the expected entry shape', () => {
    const message = rejectionOf({
      ...TITLE,
      bodySections: [
        { markdown: 'the verify config is never threaded through.' } as unknown as {
          heading: string;
          markdown: string;
        },
      ],
    }).message;
    expect(message).toContain('bodySections[0]');
    expect(message).toContain('heading');
    expect(message).toContain('{ heading: string, markdown: string }');
  });

  it('a well-formed multi-entry bare input is NOT rejected (negative control)', () => {
    expect(
      classifyCreateInput({
        ...TITLE,
        bodySections: [
          { heading: 'Gap', markdown: 'the verify config is never threaded through.' },
          { heading: 'Provenance', markdown: 'wave hardening, row 3, iteration 1.' },
        ],
      }),
    ).toEqual({ kind: 'bare' });
  });

  // Regression guard: this new per-entry shape check must not swallow the
  // OLDER `bare-without-body` failure it now runs ahead of — well-formed
  // entries whose `markdown` is blank across the board are still a content
  // question, not a shape defect, and must still be spec-pinned unchanged.
  it('does NOT reclassify the existing all-blank-markdown case — `bare-without-body` still fires', () => {
    const err = rejectionOf({
      ...TITLE,
      bodySections: [
        { heading: 'Gap', markdown: '   ' },
        { heading: 'Provenance', markdown: '' },
      ],
    });
    expect(err.failure).toBe('bare-without-body');
  });

  // Same regression guard for the "one non-blank section is enough" case: a
  // well-formed entry with blank markdown alongside a well-formed entry with
  // real content must still classify as bare, not be rejected as malformed.
  it('does NOT reject a well-formed entry whose markdown happens to be blank, alongside a real one', () => {
    expect(
      classifyCreateInput({
        ...TITLE,
        bodySections: [
          { heading: 'Gap', markdown: '   ' },
          { heading: 'Provenance', markdown: 'wave hardening, row 3, iteration 1.' },
        ],
      }),
    ).toEqual({ kind: 'bare' });
  });

  // A DECORATED input's bodySections is a lighter-weight surface (optional,
  // additive prose) and is deliberately UNTOUCHED by this bare-only rule —
  // the pinned negative control for that lives in the `classifyCreateInput`
  // shape-classification describe block above. Re-asserted here, named to
  // this issue, so a future reader who lands on THIS describe block sees the
  // boundary too.
  it('a DECORATED input with a blank-markdown bodySections entry is still classified, not rejected (#530 does not touch decorated)', () => {
    const DECORATED: CreateInput = {
      title: 'A real slice',
      filingHint: 'a-real-slice',
      risk: 'mechanical',
      worker: 'background',
      files: ['src/x.ts'],
      blockedBy: 'none',
      acceptanceCriteria: [{ text: 'does the thing', checked: false }],
      bodySections: [{ heading: 'What to build', markdown: '   ' }],
    };
    expect(classifyCreateInput(DECORATED).kind).toBe('decorated');
  });
});
