import { describe, it, expect } from 'vitest';
import {
  TRIAGE_DISCLAIMER,
  withTriageDisclaimer,
  classifyCreateInput,
  CreateInputError,
} from './issue-store';
import type { CreateInput } from './issue-store';

describe('withTriageDisclaimer (ADR-0015)', () => {
  it('prepends the verbatim AI-provenance disclaimer, blank-line separated', () => {
    expect(TRIAGE_DISCLAIMER).toBe('> *This was generated by AI during triage.*');
    expect(withTriageDisclaimer('Agent Brief here')).toBe(
      '> *This was generated by AI during triage.*\n\nAgent Brief here',
    );
  });
});

// ── classifyCreateInput — the whole-input create contract (ADR-0027, #278/#309)
//
// These are the LAYER specs: the classifier is called directly, with no store
// and no CLI in the picture at all, because that is the claim under test — the
// create-shape invariants are properties of this function, so every caller
// (every adapter's `create()`, the issue-store CLI, any future driver) inherits
// them rather than re-deriving one of them at its own edge.
describe('classifyCreateInput (ADR-0027) — shape classification', () => {
  const BARE: CreateInput = {
    title: 'Gate 8 ships inert',
    filingHint: 'gate-8-ships-inert',
    bodySections: [
      { heading: 'Gap', markdown: 'the verify config is never threaded through.' },
      { heading: 'Provenance', markdown: 'wave hardening, row 3, iteration 1.' },
    ],
  };

  const DECORATED: CreateInput = {
    title: 'A real slice',
    filingHint: 'a-real-slice',
    risk: 'mechanical',
    worker: 'background',
    files: ['src/x.ts'],
    blockedBy: 'none',
    acceptanceCriteria: [{ text: 'does the thing', checked: false }],
  };

  it('classifies a bare input (title + filingHint + authored bodySections) as bare', () => {
    expect(classifyCreateInput(BARE)).toEqual({ kind: 'bare' });
  });

  it('classifies a full Header-Block as decorated and hands back the narrowed input', () => {
    const shape = classifyCreateInput(DECORATED);
    expect(shape.kind).toBe('decorated');
    if (shape.kind === 'decorated') expect(shape.input.risk).toBe('mechanical');
  });

  // The negative control for the bare-body rule below: `bodySections` is
  // optional for a DECORATED input and must STAY optional — a decorated issue
  // has a Header-Block, so it is never a 0-body-char filing. If the requirement
  // ever leaks out of the bare branch, this is the case that fails.
  it('a DECORATED input with NO bodySections is still classified, not rejected', () => {
    expect(DECORATED.bodySections).toBeUndefined();
    expect(classifyCreateInput(DECORATED).kind).toBe('decorated');
    expect(classifyCreateInput({ ...DECORATED, bodySections: [] }).kind).toBe('decorated');
    expect(
      classifyCreateInput({
        ...DECORATED,
        bodySections: [{ heading: 'What to build', markdown: '   ' }],
      }).kind,
    ).toBe('decorated');
  });
});

// The typed rejection below is PUBLIC API as of issue #325: `CreateInputError`
// and `CreateInputFailure` are re-exported from the package root. Its pairing —
// same class binding across the barrel, so a root consumer's `instanceof` matches
// what these adapters throw — is asserted in `index.spec.ts`, the file that owns
// pairings spanning more than one module. These stay the LAYER specs: what the
// classifier rejects and why, with no barrel in the picture.
describe('classifyCreateInput — typed rejections (#309: the classifier owns the invariant)', () => {
  /** Run the classifier and return the CreateInputError it threw. */
  function rejectionOf(input: CreateInput): CreateInputError {
    try {
      classifyCreateInput(input);
    } catch (err) {
      expect(err).toBeInstanceOf(CreateInputError);
      return err as CreateInputError;
    }
    throw new Error('expected classifyCreateInput to reject, but it returned');
  }

  const TITLE = { title: 'Gate 8 ships inert', filingHint: 'gate-8-ships-inert' };

  it('a BARE input with bodySections ABSENT is rejected as `bare-without-body`', () => {
    const err = rejectionOf({ ...TITLE });
    expect(err.failure).toBe('bare-without-body');
    expect(err.fields).toEqual(['bodySections']);
    expect(err.code).toBe('create-input-invalid');
    expect(err.name).toBe('CreateInputError');
  });

  it('a BARE input with bodySections `[]` is rejected the same way', () => {
    expect(rejectionOf({ ...TITLE, bodySections: [] }).failure).toBe('bare-without-body');
  });

  it('a BARE input whose bodySections markdown is ALL BLANK is rejected the same way', () => {
    const err = rejectionOf({
      ...TITLE,
      bodySections: [
        { heading: 'Gap', markdown: '   ' },
        { heading: 'Provenance', markdown: '' },
      ],
    });
    expect(err.failure).toBe('bare-without-body');
  });

  it('ONE non-blank section is enough — the rule asks for authored content, not for every section to carry it', () => {
    expect(
      classifyCreateInput({
        ...TITLE,
        bodySections: [
          { heading: 'Gap', markdown: '   ' },
          { heading: 'Provenance', markdown: 'wave hardening, row 3, iteration 1.' },
        ],
      }),
    ).toEqual({ kind: 'bare' });
  });

  // Message quality is what the CLI renders; the rejection is what it routes on.
  // Both are pinned here so the layer move cannot quietly degrade the operator-
  // facing text into a bare "invalid input".
  it('the bare-body message names the field to fix and what would otherwise be filed', () => {
    const message = rejectionOf({ ...TITLE }).message;
    expect(message).toContain('bodySections');
    expect(message).toContain('no body at all');
    expect(message).toContain('Header-Block');
  });

  it('a HALF-WRITTEN Header-Block is rejected as `header-block-half-written`, naming the missing fields', () => {
    const err = rejectionOf({ ...TITLE, risk: 'mechanical' });
    expect(err.failure).toBe('header-block-half-written');
    expect(err.fields).toEqual(['worker', 'files', 'blockedBy', 'acceptanceCriteria']);
    expect(err.message).toMatch(/half-written/i);
  });

  it('a decoration-only stowaway on a bare input is rejected as `bare-carries-decoration-only-fields`', () => {
    const err = rejectionOf({ ...TITLE, parent: 'some-prd-id' });
    expect(err.failure).toBe('bare-carries-decoration-only-fields');
    expect(err.fields).toEqual(['parent']);
  });

  // Precedence: the stowaway verdict is the more specific claim about a
  // bodyless bare input, so it must not be masked by the body rule.
  it('a bodyless bare input carrying a stowaway reports the stowaway, not the missing body', () => {
    expect(rejectionOf({ ...TITLE, unblocks: [{ issue: 7 }] }).failure).toBe(
      'bare-carries-decoration-only-fields',
    );
  });

  it('every rejection is a real Error subclass (catchable by generic handlers too)', () => {
    const err = rejectionOf({ ...TITLE });
    expect(err).toBeInstanceOf(Error);
    expect(err.stack).toBeTruthy();
  });
});
