import { describe, it, expect } from 'vitest';
import { TRIAGE_DISCLAIMER, withTriageDisclaimer } from './issue-store';

describe('withTriageDisclaimer (ADR-0015)', () => {
  it('prepends the verbatim AI-provenance disclaimer, blank-line separated', () => {
    expect(TRIAGE_DISCLAIMER).toBe('> *This was generated by AI during triage.*');
    expect(withTriageDisclaimer('Agent Brief here')).toBe(
      '> *This was generated by AI during triage.*\n\nAgent Brief here',
    );
  });
});
