/**
 * triage-facet.spec.ts — ADR-0015 cross-store contract net.
 *
 * The same assertions over BOTH shipped stores are the guarantee that the
 * Triage facet is tracker-agnostic. Scope is the pre-wave triage lifecycle
 * (open issues) + the closeUnplanned terminal — NOT post-wave-close triage
 * state (MarkdownFs repurposes **Status:** on wave-close; out of scope).
 */
import { describe, it, expect, afterAll } from 'vitest';
import { mkdtemp, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { MarkdownFsStore } from './markdown-fs-store';
import { GitHubIssuesStore } from './github/github-issues-store';
import { InMemoryGitHubApi } from './github/github-api-fake';
import { LinearIssuesStore } from './linear/linear-issues-store';
import { InMemoryLinearApi } from './linear/linear-api-fake';
import type { CreateInput, IssueStore } from './issue-store';

const SLUG = 'tri-facet';
const tmpRoots: string[] = [];
afterAll(async () => {
  await Promise.all(tmpRoots.map((r) => rm(r, { recursive: true, force: true })));
});

function baseInput(overrides: Partial<CreateInput> = {}): CreateInput {
  return {
    title: 'A slice',
    filingHint: 'a-slice',
    risk: 'mechanical',
    worker: 'background',
    files: ['src/x.ts'],
    blockedBy: 'none',
    acceptanceCriteria: [{ text: 'does the thing', checked: false }],
    ...overrides,
  };
}

const stores: { name: string; make: () => Promise<IssueStore> }[] = [
  {
    name: 'MarkdownFsStore',
    make: async () => {
      const root = await mkdtemp(join(tmpdir(), 'trifacet-'));
      tmpRoots.push(root);
      return new MarkdownFsStore({ repoRoot: root, slug: SLUG });
    },
  },
  {
    name: 'GitHubIssuesStore',
    make: async () => new GitHubIssuesStore({ api: new InMemoryGitHubApi() }),
  },
  {
    name: 'LinearIssuesStore',
    make: async () => new LinearIssuesStore({ api: new InMemoryLinearApi() }),
  },
];

const DISCLAIMER = '> *This was generated by AI during triage.*';

for (const { name, make } of stores) {
  describe(`${name} — Triage facet (ADR-0015)`, () => {
    it('readTriage surfaces the issue title and body so the agent can triage the report', async () => {
      // The triage agent reads the reported content through the facet — no raw
      // `gh issue view` (ADR-0015). IssueView omits title/body (wave-header only);
      // TriageView carries them so the read path is tracker-agnostic too.
      const store = await make();
      const id = await store.create(
        baseInput({
          title: 'Login button does nothing',
          bodySections: [{ heading: 'What to build', markdown: 'clicking login is a no-op' }],
        }),
      );
      const t = await store.readTriage(id);
      expect(t.title).toBe('Login button does nothing');
      expect(t.body).toContain('clicking login is a no-op');
    });

    it('applyTriage(state, category, comment) round-trips through readTriage', async () => {
      const store = await make();
      const id = await store.create(baseInput());
      await store.applyTriage(id, { state: 'needs-info', category: 'bug', comment: 'need a repro' });
      const t = await store.readTriage(id);
      expect(t.state).toBe('needs-info');
      expect(t.category).toBe('bug');
      expect(t.comments[0].body).toBe(`${DISCLAIMER}\n\nneed a repro`);
    });

    it('state is single-select (a second applyTriage replaces the first)', async () => {
      const store = await make();
      const id = await store.create(baseInput());
      await store.applyTriage(id, { state: 'needs-info' });
      await store.applyTriage(id, { state: 'ready-for-human' });
      expect((await store.readTriage(id)).state).toBe('ready-for-human');
    });

    it('the triage state IS the eligibility coupling (ADR-0003)', async () => {
      const store = await make();
      const id = await store.create(baseInput()); // create stamps ready-for-agent
      expect((await store.listOpen('wave-ready')).map((v) => v.id)).toContain(id);
      await store.applyTriage(id, { state: 'needs-info' });
      expect((await store.listOpen('wave-ready')).map((v) => v.id)).not.toContain(id);
      await store.applyTriage(id, { state: 'ready-for-agent' });
      expect((await store.listOpen('wave-ready')).map((v) => v.id)).toContain(id);
    });

    it('applyTriage rejects out-of-vocab state and category', async () => {
      const store = await make();
      const id = await store.create(baseInput());
      await expect(store.applyTriage(id, { state: 'bogus' })).rejects.toThrow();
      await expect(store.applyTriage(id, { category: 'bogus' })).rejects.toThrow();
    });

    it('closeUnplanned → status done, triage state wontfix, comment recorded', async () => {
      const store = await make();
      const id = await store.create(baseInput());
      await store.closeUnplanned(id, 'out of scope');
      expect((await store.read(id)).status).toBe('done');
      expect((await store.readTriage(id)).state).toBe('wontfix');
      expect((await store.readTriage(id)).comments[0].body).toContain('out of scope');
    });

    it('triage state never leaks into IssueView.status (ADR-0003)', async () => {
      const store = await make();
      const id = await store.create(baseInput());
      await store.applyTriage(id, { state: 'needs-info' });
      const view = await store.read(id);
      expect(['available', 'queued', 'in-flight', 'in-review', 'done', 'needs-attention'])
        .toContain(view.status);
      expect(view.status).not.toBe('needs-info');
    });
  });
}
